// apps/frontend/src/app/layout.tsx
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { useAuthStore } from "../src/store/useAuthStore"; // import store

// --- Fonts ---
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMonoFont = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// --- Metadata ---
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// --- Root Layout ---
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  // Initialize Auth store (SSR safe)
  useAuthStore.getState().initialize();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMonoFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}