import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthInitializer from "./test-auth/AuthInitializer"; // client component

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthInitializer /> {/* Client-side auth initialization */}
        {children}
      </body>
    </html>
  );
}
